### ISSUE TITLE
IE10: Not working properly

### ISSUE THREAD

**Issue by madhuinwiter** [Geta/angular-timepicker#14] opened 2014-12-13 04:41 UTC
Hello,

The directive you have provided is simple and good. I have an issue in IE 10. 

That is If we click on input box it's getting displayed and again hiding immediately.  Can you please take a look and help me to fix this.

Thanks for your time

**Comment by anied** [comment] 2015-11-30 16:55
I also am seeing this issue.

**Comment by anied** [comment] 2015-11-30 20:43
Nevermind, I realized the project uses an older version of the library-- the issue is fixed in 1.0.3.  Updating all the way to the current version (1.0.8) yielded a host of new issues, which was unexpected, but perhaps this project isn't following <a href="http://semver.org/" target="_blank">Semver</a>?  Anyway, @madhuinwiter I would suggest trying to see if you are using a version prior to 1.0.3 and update to that and see if the problem is solved.  If so, @dnasir can probably close this issue.

**Closed** 2017-03-20 07:55 UTC
